# Generated by Django 5.1.2 on 2025-01-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together=set(),
        ),
    ]
