# Generated by Django 5.1.2 on 2025-01-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_alter_coursemember_unique_together_contentcompletion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentCompletion',
        ),
    ]
